name: Dependency-Check

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (required for OWASP Dependency-Check)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Latest OpenJDK
          java-version: '17' # Use the latest LTS version

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'MyProject'
          path: './'
          format: 'HTML'

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
